/**
 * Landing page HTML — generated by Google Stitch, served at /
 */
export function getLandingHtml(): string {
  return LANDING_HTML;
}

const LANDING_HTML = `
<!DOCTYPE html>

<html class="dark" lang="en"><head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<title>mflow | Real-time code sync for AI agent teams</title>
<script src="https://cdn.tailwindcss.com?plugins=forms,container-queries"></script>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&amp;family=JetBrains+Mono:wght@400;500&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght@100..700,0..1&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&amp;display=swap" rel="stylesheet"/>
<script id="tailwind-config">
        tailwind.config = {
            darkMode: "class",
            theme: {
                extend: {
                    colors: {
                        "primary": "#10b981",
                        "background-light": "#f6f8f7",
                        "background-dark": "#0a0a0a",
                        "neutral-dark": "#171717",
                        "text-main": "#fafafa",
                        "text-muted": "#737373"
                    },
                    fontFamily: {
                        "display": ["Inter", "sans-serif"],
                        "mono": ["JetBrains Mono", "monospace"]
                    },
                    borderRadius: {
                        "DEFAULT": "0.25rem",
                        "lg": "0.5rem",
                        "xl": "0.75rem",
                        "full": "9999px"
                    },
                },
            },
        }
    </script>
</head>
<body class="bg-background-light dark:bg-background-dark font-display text-slate-900 dark:text-text-main antialiased selection:bg-primary/30">
<header class="fixed top-0 w-full z-50 border-b border-white/5 bg-background-dark/80 backdrop-blur-md">
<div class="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
<div class="flex items-center gap-2">
<span class="text-xl font-bold tracking-tight text-text-main">mflow</span>
</div>
<nav class="hidden md:flex items-center gap-8">
<a class="text-sm font-medium text-text-muted hover:text-primary transition-colors" href="#">GitHub</a>
<a class="text-sm font-medium text-text-muted hover:text-primary transition-colors" href="#">Docs</a>
<a class="text-sm font-medium text-text-muted hover:text-primary transition-colors" href="#">Monitor</a>
</nav>
<div class="flex items-center gap-4">
<button class="bg-primary hover:bg-primary/90 text-background-dark px-4 py-2 rounded-lg text-sm font-bold transition-all">
                    Get Started
                </button>
</div>
</div>
</header>
<main class="pt-32 pb-20">
<section class="max-w-7xl mx-auto px-6 mb-32">
<div class="grid lg:grid-cols-2 gap-16 items-center">
<div class="flex flex-col gap-8">
<h1 class="text-6xl md:text-7xl font-black tracking-tighter text-text-main leading-[1.1]">
                        Real-time code sync for AI agent teams
                    </h1>
<p class="text-lg md:text-xl text-text-muted leading-relaxed max-w-xl">
                        5 agents edit the same codebase simultaneously. Zero merge conflicts. Encrypted end-to-end.
                    </p>
<div class="flex flex-wrap gap-4">
<button class="bg-primary hover:bg-primary/90 text-background-dark px-8 py-4 rounded-xl text-base font-bold transition-all shadow-lg shadow-primary/10">
                            Get Started
                        </button>
<button class="border border-white/10 hover:border-primary/50 hover:bg-primary/5 text-text-main px-8 py-4 rounded-xl text-base font-bold transition-all">
                            View on GitHub
                        </button>
</div>
</div>
<div class="relative">
<div class="absolute -inset-1 bg-gradient-to-r from-primary/20 to-transparent blur-2xl opacity-50"></div>
<div class="relative bg-neutral-dark border border-white/10 rounded-xl overflow-hidden shadow-2xl">
<div class="flex items-center gap-1.5 px-4 py-3 border-b border-white/5 bg-white/5">
<div class="w-3 h-3 rounded-full bg-red-500/20 border border-red-500/50"></div>
<div class="w-3 h-3 rounded-full bg-yellow-500/20 border border-yellow-500/50"></div>
<div class="w-3 h-3 rounded-full bg-green-500/20 border border-green-500/50"></div>
<span class="ml-2 text-xs font-mono text-text-muted">bash — mflow</span>
</div>
<div class="p-6 font-mono text-sm leading-relaxed space-y-1">
<p class="text-text-main"><span class="text-primary">\$</span> mflow start --room my-project --secret my-secret</p>
<p class="text-primary">✓ Connected to room (2 peers)</p>
<p class="text-text-muted">↑ src/auth.ts synced → 3 peers</p>
<p class="text-text-muted">↑ src/routes.ts created → 2 peers</p>
<div class="h-4 w-2 bg-primary inline-block animate-pulse ml-1"></div>
</div>
</div>
</div>
</div>
</section>
<section class="max-w-7xl mx-auto px-6 mb-32">
<div class="mb-12">
<h2 class="text-3xl font-bold tracking-tight mb-4">How it works</h2>
<p class="text-text-muted">Experience seamless collaboration without version control overhead.</p>
</div>
<div class="grid md:grid-cols-3 gap-6">
<div class="bg-neutral-dark border border-white/5 p-8 rounded-2xl hover:border-primary/30 transition-colors group">
<span class="material-symbols-outlined text-primary mb-4 text-3xl group-hover:scale-110 transition-transform">sync_alt</span>
<h3 class="text-xl font-bold mb-3">Sync</h3>
<p class="text-text-muted leading-relaxed">File changes propagate in &lt;1 second between all peers. No git, no commits, no merges.</p>
</div>
<div class="bg-neutral-dark border border-white/5 p-8 rounded-2xl hover:border-primary/30 transition-colors group">
<span class="material-symbols-outlined text-primary mb-4 text-3xl group-hover:scale-110 transition-transform">encrypted</span>
<h3 class="text-xl font-bold mb-3">Encrypt</h3>
<p class="text-text-muted leading-relaxed">AES-256-GCM end-to-end. The server never sees your code. Only encrypted bytes pass through.</p>
</div>
<div class="bg-neutral-dark border border-white/5 p-8 rounded-2xl hover:border-primary/30 transition-colors group">
<span class="material-symbols-outlined text-primary mb-4 text-3xl group-hover:scale-110 transition-transform">lock_person</span>
<h3 class="text-xl font-bold mb-3">Prevent</h3>
<p class="text-text-muted leading-relaxed">Propagation gate automatically queues concurrent edits. File locks for coordinated workflows.</p>
</div>
</div>
</section>
<section class="max-w-7xl mx-auto px-6 mb-32">
<div class="bg-neutral-dark border border-white/5 rounded-3xl overflow-hidden">
<div class="grid lg:grid-cols-2">
<div class="p-12 flex flex-col justify-center gap-6">
<div>
<h2 class="text-3xl font-bold mb-4">Monitor your sync room</h2>
<p class="text-text-muted text-lg mb-6">See who's connected, what files are syncing, and activity in real-time through a centralized dashboard.</p>
<p class="font-mono text-sm text-primary/60 mb-8 break-all">https://mflow-signal.obed0101.deno.net/dashboard</p>
</div>
<button class="bg-primary hover:bg-primary/90 text-background-dark px-6 py-3 rounded-xl font-bold w-fit transition-all">
                            Open Monitor
                        </button>
</div>
<div class="bg-gradient-to-br from-neutral-dark to-primary/10 p-4 lg:p-12 relative overflow-hidden flex items-center justify-center min-h-[300px]" data-alt="Abstract UI dashboard representation with neon green accents">
<div class="w-full h-full rounded-xl bg-background-dark/60 border border-white/10 p-6 font-mono text-xs">
<div class="flex justify-between items-center mb-6">
<div class="text-primary">SIGNAL SERVER: ACTIVE</div>
<div class="text-text-muted">UPTIME: 99.9%</div>
</div>
<div class="space-y-3">
<div class="flex gap-4">
<span class="text-primary">[PEER 1]</span>
<span>agent-alpha connected</span>
</div>
<div class="flex gap-4">
<span class="text-primary">[SYNC]</span>
<span>main.py (4.2kb) → 4 peers</span>
</div>
<div class="flex gap-4">
<span class="text-primary">[LOCK]</span>
<span>db.ts locked by agent-beta</span>
</div>
<div class="flex gap-4 opacity-50">
<span class="text-primary">[PEER 2]</span>
<span>agent-gamma join request...</span>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section class="max-w-7xl mx-auto px-6 mb-32">
<div class="mb-12">
<h2 class="text-3xl font-bold tracking-tight mb-4 text-center">Built for scale and security</h2>
</div>
<div class="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
<div class="p-6 rounded-2xl border border-white/5 bg-neutral-dark/40">
<h4 class="text-text-main font-bold mb-2">MCP Server</h4>
<p class="text-sm text-text-muted">Native support for Model Context Protocol to bridge AI tools and local files seamlessly.</p>
</div>
<div class="p-6 rounded-2xl border border-white/5 bg-neutral-dark/40">
<h4 class="text-text-main font-bold mb-2">File Locking</h4>
<p class="text-sm text-text-muted">Prevents race conditions by allowing agents to exclusively lock files during intensive tasks.</p>
</div>
<div class="p-6 rounded-2xl border border-white/5 bg-neutral-dark/40">
<h4 class="text-text-main font-bold mb-2">CLI Dashboard</h4>
<p class="text-sm text-text-muted">A full TUI experience directly in your terminal to monitor health and peer status.</p>
</div>
<div class="p-6 rounded-2xl border border-white/5 bg-neutral-dark/40">
<h4 class="text-text-main font-bold mb-2">Self-Hosted</h4>
<p class="text-sm text-text-muted">Run your own signal server on any infrastructure for maximum privacy and control.</p>
</div>
<div class="p-6 rounded-2xl border border-white/5 bg-neutral-dark/40">
<h4 class="text-text-main font-bold mb-2">Zero Config</h4>
<p class="text-sm text-text-muted">Start syncing in seconds with sensible defaults that work out of the box for any project.</p>
</div>
<div class="p-6 rounded-2xl border border-white/5 bg-neutral-dark/40">
<h4 class="text-text-main font-bold mb-2">Open Source</h4>
<p class="text-sm text-text-muted">MIT licensed core. Audit the code, contribute, or fork it to meet your team's unique needs.</p>
</div>
</div>
</section>
<section class="max-w-7xl mx-auto px-6 mb-32">
<h2 class="text-3xl font-bold tracking-tight mb-12 text-center">Quick Start</h2>
<div class="grid lg:grid-cols-3 gap-6">
<div class="flex flex-col gap-4">
<h3 class="text-sm font-bold text-primary uppercase tracking-wider">1. Install</h3>
<div class="bg-neutral-dark p-4 rounded-lg font-mono text-sm border border-white/10">
<span class="text-text-muted"># Using npm</span><br/>
<span class="text-text-main">npm i -g mflow</span>
</div>
</div>
<div class="flex flex-col gap-4">
<h3 class="text-sm font-bold text-primary uppercase tracking-wider">2. Start syncing</h3>
<div class="bg-neutral-dark p-4 rounded-lg font-mono text-sm border border-white/10">
<span class="text-text-muted"># From project root</span><br/>
<span class="text-text-main">mflow start --room project-x</span>
</div>
</div>
<div class="flex flex-col gap-4">
<h3 class="text-sm font-bold text-primary uppercase tracking-wider">3. Join room</h3>
<div class="bg-neutral-dark p-4 rounded-lg font-mono text-sm border border-white/10">
<span class="text-text-muted"># On another machine</span><br/>
<span class="text-text-main">mflow join --room project-x</span>
</div>
</div>
</div>
</section>
</main>
<footer class="border-t border-white/5 bg-neutral-dark/30 py-16">
<div class="max-w-7xl mx-auto px-6">
<div class="flex flex-col md:flex-row justify-between items-start gap-12 mb-12">
<div class="flex flex-col gap-4">
<span class="text-2xl font-bold tracking-tight text-text-main">mflow</span>
<p class="text-text-muted max-w-xs text-sm">Real-time collaboration for the next generation of AI development teams.</p>
</div>
<div class="grid grid-cols-2 md:grid-cols-3 gap-12">
<div class="flex flex-col gap-4">
<span class="text-xs font-bold text-text-main uppercase">Resources</span>
<a class="text-sm text-text-muted hover:text-primary transition-colors" href="#">GitHub</a>
<a class="text-sm text-text-muted hover:text-primary transition-colors" href="#">Documentation</a>
</div>
<div class="flex flex-col gap-4">
<span class="text-xs font-bold text-text-main uppercase">Product</span>
<a class="text-sm text-text-muted hover:text-primary transition-colors" href="#">Monitor</a>
<a class="text-sm text-text-muted hover:text-primary transition-colors" href="#">Changelog</a>
</div>
<div class="flex flex-col gap-4">
<span class="text-xs font-bold text-text-main uppercase">Legal</span>
<span class="text-sm text-text-muted">MIT License</span>
</div>
</div>
</div>
<div class="flex flex-col md:flex-row justify-between items-center pt-8 border-t border-white/5 gap-4">
<p class="text-sm text-text-muted">Made for AI agent teams.</p>
<div class="flex gap-6">
<span class="material-symbols-outlined text-text-muted hover:text-primary cursor-pointer text-xl">terminal</span>
<span class="material-symbols-outlined text-text-muted hover:text-primary cursor-pointer text-xl">share</span>
</div>
</div>
</div>
</footer>
</body></html>`;
