import { EventEmitter } from "node:events";
import * as Y from "yjs";
import { computeDiff, applyDiffToYText, YDOC_UNLOAD_MINUTES } from "../../shared/src/index.js";

// ─── Types ──────────────────────────────────────────────────

export interface TrackedFile {
  path: string;
  doc: Y.Doc | null;
  text: Y.Text | null;
  lastAccess: number;
  contentHash: string;
  persisted: boolean;
}

export interface CRDTManagerEvents {
  "local-update": (path: string, update: Uint8Array) => void;
  "remote-content": (path: string, content: string, hash: string) => void;
  "doc-loaded": (path: string) => void;
  "doc-unloaded": (path: string) => void;
}

/** Persistence interface — injected to avoid circular deps. */
export interface ICRDTPersistence {
  saveDoc(path: string, state: Uint8Array): Promise<void>;
  loadDoc(path: string): Promise<Uint8Array | null>;
}

// ─── CRDTManager ────────────────────────────────────────────

/**
 * Manages Y.Doc instances with lazy loading and automatic unloading.
 *
 * One Y.Doc per tracked file. Docs are loaded on first access and
 * unloaded after `unloadAfterMinutes` of inactivity (if persisted).
 */
export class CRDTManager extends EventEmitter {
  private readonly files = new Map<string, TrackedFile>();
  private readonly unloadAfterMs: number;
  private unloadTimer: ReturnType<typeof setInterval> | null = null;

  constructor(unloadAfterMinutes: number = YDOC_UNLOAD_MINUTES) {
    super();
    this.unloadAfterMs = unloadAfterMinutes * 60_000;
  }

  // ─── Doc Lifecycle ──────────────────────────────────────

  /**
   * Get or create a Y.Doc + Y.Text for a file path.
   * Marks the file as recently accessed.
   */
  ensureDoc(path: string): { doc: Y.Doc; text: Y.Text } {
    let tracked = this.files.get(path);

    if (!tracked) {
      tracked = {
        path,
        doc: null,
        text: null,
        lastAccess: Date.now(),
        contentHash: "",
        persisted: false,
      };
      this.files.set(path, tracked);
    }

    if (!tracked.doc) {
      const doc = new Y.Doc();
      const text = doc.getText("content");

      // Listen for updates originating from local transactions
      doc.on("update", (update: Uint8Array, origin: unknown) => {
        if (origin === "local") {
          this.emit("local-update", path, update);
        }
      });

      tracked.doc = doc;
      tracked.text = text;
      tracked.persisted = false;
      this.emit("doc-loaded", path);
    }

    tracked.lastAccess = Date.now();
    return { doc: tracked.doc, text: tracked.text! };
  }

  /**
   * Restore a Y.Doc from persisted state (Uint8Array from persistence layer).
   */
  restoreDoc(path: string, state: Uint8Array): { doc: Y.Doc; text: Y.Text } {
    const { doc, text } = this.ensureDoc(path);
    Y.applyUpdate(doc, state);
    return { doc, text };
  }

  /**
   * Check if a doc exists and is loaded for the given path.
   */
  hasDoc(path: string): boolean {
    const tracked = this.files.get(path);
    return tracked !== undefined && tracked.doc !== null;
  }

  /**
   * Get the tracked file entry (if any).
   */
  getTracked(path: string): TrackedFile | undefined {
    return this.files.get(path);
  }

  /**
   * Get all currently tracked file paths.
   */
  getTrackedPaths(): string[] {
    return [...this.files.keys()];
  }

  /**
   * Get count of actively loaded (non-null doc) files.
   */
  getActiveDocCount(): number {
    let count = 0;
    for (const tracked of this.files.values()) {
      if (tracked.doc !== null) count++;
    }
    return count;
  }

  // ─── Local Changes ──────────────────────────────────────

  /**
   * Apply a local file change by computing a diff and applying it to Y.Text.
   *
   * @returns The Y.js update binary to broadcast, or null if no diff.
   */
  applyLocalChange(
    path: string,
    oldContent: string,
    newContent: string,
    contentHash: string,
  ): Uint8Array | null {
    const ops = computeDiff(oldContent, newContent);
    if (ops.length === 0) return null;

    const { doc, text } = this.ensureDoc(path);
    const tracked = this.files.get(path)!;
    tracked.contentHash = contentHash;
    tracked.persisted = false;

    let update: Uint8Array | null = null;

    // Capture the update generated by this transaction
    const captureUpdate = (u: Uint8Array, origin: unknown) => {
      if (origin === "local") {
        update = u;
      }
    };
    doc.on("update", captureUpdate);

    doc.transact(() => {
      applyDiffToYText(text, ops);
    }, "local");

    doc.off("update", captureUpdate);

    return update;
  }

  /**
   * Initialize a Y.Text with full content (for new files or first load).
   *
   * @returns The Y.js update binary to broadcast.
   */
  initializeContent(path: string, content: string, contentHash: string): Uint8Array {
    const { doc, text } = this.ensureDoc(path);
    const tracked = this.files.get(path)!;
    tracked.contentHash = contentHash;
    tracked.persisted = false;

    let update: Uint8Array = new Uint8Array(0);

    const captureUpdate = (u: Uint8Array, origin: unknown) => {
      if (origin === "local") {
        update = u;
      }
    };
    doc.on("update", captureUpdate);

    doc.transact(() => {
      if (text.length > 0) {
        text.delete(0, text.length);
      }
      text.insert(0, content);
    }, "local");

    doc.off("update", captureUpdate);

    return update;
  }

  // ─── Remote Changes ─────────────────────────────────────

  /**
   * Apply a remote Y.js update to a file's doc.
   *
   * @returns The merged content string after applying the update.
   */
  applyRemoteUpdate(path: string, update: Uint8Array): string {
    const { doc, text } = this.ensureDoc(path);
    const tracked = this.files.get(path)!;

    Y.applyUpdate(doc, update, "remote");

    const content = text.toString();
    tracked.persisted = false;
    tracked.lastAccess = Date.now();

    return content;
  }

  // ─── Content Access ─────────────────────────────────────

  /**
   * Get the current Y.Text content for a file.
   * Returns null if the file is not tracked or doc is unloaded.
   */
  getContent(path: string): string | null {
    const tracked = this.files.get(path);
    if (!tracked?.text) return null;
    tracked.lastAccess = Date.now();
    return tracked.text.toString();
  }

  /**
   * Get the full Y.Doc state as a binary update (for sync protocol).
   */
  encodeState(path: string): Uint8Array | null {
    const tracked = this.files.get(path);
    if (!tracked?.doc) return null;
    return Y.encodeStateAsUpdate(tracked.doc);
  }

  /**
   * Get the state vector for a file's doc (for sync protocol).
   */
  encodeStateVector(path: string): Uint8Array | null {
    const tracked = this.files.get(path);
    if (!tracked?.doc) return null;
    return Y.encodeStateVector(tracked.doc);
  }

  // ─── Unloading ──────────────────────────────────────────

  /**
   * Start the periodic idle-doc unload timer.
   */
  startUnloadTimer(persistence: ICRDTPersistence): void {
    if (this.unloadTimer) return;

    // Check every minute
    this.unloadTimer = setInterval(() => {
      void this.unloadIdle(persistence);
    }, 60_000);
  }

  /**
   * Stop the unload timer.
   */
  stopUnloadTimer(): void {
    if (this.unloadTimer) {
      clearInterval(this.unloadTimer);
      this.unloadTimer = null;
    }
  }

  /**
   * Unload Y.Docs that haven't been accessed within the unload window.
   * Persists state before unloading.
   */
  async unloadIdle(persistence: ICRDTPersistence): Promise<number> {
    const now = Date.now();
    let unloaded = 0;

    for (const tracked of this.files.values()) {
      if (!tracked.doc) continue;
      if (now - tracked.lastAccess < this.unloadAfterMs) continue;

      await this.unloadDoc(tracked.path, persistence);
      unloaded++;
    }

    return unloaded;
  }

  /**
   * Persist and unload a specific doc.
   */
  async unloadDoc(path: string, persistence: ICRDTPersistence): Promise<void> {
    const tracked = this.files.get(path);
    if (!tracked?.doc) return;

    // Persist state before unloading
    const state = Y.encodeStateAsUpdate(tracked.doc);
    await persistence.saveDoc(path, state);

    tracked.doc.destroy();
    tracked.doc = null;
    tracked.text = null;
    tracked.persisted = true;

    this.emit("doc-unloaded", path);
  }

  /**
   * Persist all loaded docs (for graceful shutdown).
   */
  async persistAll(persistence: ICRDTPersistence): Promise<void> {
    for (const tracked of this.files.values()) {
      if (!tracked.doc || tracked.persisted) continue;

      const state = Y.encodeStateAsUpdate(tracked.doc);
      await persistence.saveDoc(tracked.path, state);
      tracked.persisted = true;
    }
  }

  // ─── Removal ────────────────────────────────────────────

  /**
   * Remove a file from tracking entirely (e.g., file deleted).
   */
  removeFile(path: string): void {
    const tracked = this.files.get(path);
    if (tracked?.doc) {
      tracked.doc.destroy();
    }
    this.files.delete(path);
  }

  // ─── Lifecycle ──────────────────────────────────────────

  /**
   * Clean up all docs and timers.
   */
  dispose(): void {
    this.stopUnloadTimer();

    for (const tracked of this.files.values()) {
      if (tracked.doc) {
        tracked.doc.destroy();
        tracked.doc = null;
        tracked.text = null;
      }
    }

    this.files.clear();
    this.removeAllListeners();
  }
}
